package com.asciistudio.mobile.core.model

data class RenderSettings(
    val widthChars: Int = 120,
    val charAspectRatio: Float = 0.55f,
    val fontSizeSp: Float = 8.5f,
    val contrast: Float = 1f,
    val brightness: Float = 0f,
    val gamma: Float = 1f,
    val saturation: Float = 1f,
    val exposure: Float = 0f,
    val sharpen: Float = 0f,
    val vignette: Float = 0f,
    val bloom: Float = 0f,
    val denoise: Float = 0f,
    val edgeBoost: Float = 0f,
    val posterize: Int = 0,
    val scanlines: Boolean = false,
    val scanStrength: Float = 0.22f,
    val scanStep: Int = 3,
    val dither: Boolean = false,
    val curvature: Float = 0f,
    val concavity: Float = 0f,
    val curveCenterX: Float = 0f,
    val curveExpand: Float = 0f,
    val curveType: Int = 0,
    val grain: Float = 0f,
    val chroma: Float = 0f,
    val ribbing: Float = 0f,
    val clarity: Float = 0f,
    val motionBlur: Float = 0f,
    val colorBoost: Float = 0f,
    val glitch: Float = 0f,
    val glitchDensity: Float = 0.35f,
    val glitchShift: Float = 0.42f,
    val glitchRgb: Boolean = true,
    val glitchBlock: Float = 0.10f,
    val glitchJitter: Float = 0.10f,
    val glitchNoise: Float = 0.12f,
    val invert: Boolean = false,
    val preserveSourceColors: Boolean = false,
    val charsetKey: String = "Classic",
    val charsetValue: String = "@%#*+=-:. ",
    val watermarkEnabled: Boolean = false,
    val watermarkText: String = "SNERK503",
    val renderFps: Int = 24,
    val renderCodec: String = "libx264",
    val renderBitrate: String = "2M",
    val exportFormat: String = "PNG"
)

enum class PreviewQuality(val id: String, val widthScale: Float) {
    Draft("draft", 0.62f),
    Normal("normal", 1.0f),
    High("high", 1.24f)
}
